export const bancoPerguntas = [
    { pergunta: "De quem é a habilidade 'Sentença'?", opcoes: ["Thresh", "Blitzcrank", "Nautilus", "Pyke"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Puxão Biônico'?", opcoes: ["Blitzcrank", "Thresh", "Nautilus", "Viktor"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Sifão de Ataque'?", opcoes: ["Nasus", "Veigar", "Sion", "Renekton"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Justiça Demaciana'?", opcoes: ["Garen", "Jarvan IV", "Lux", "Xin Zhao"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Lótus da Morte'?", opcoes: ["Katarina", "Samira", "Akali", "Cassiopeia"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Barril de Pólvora'?", opcoes: ["Gangplank", "Gragas", "Ziggs", "Corki"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Crescimento Gigante'?", opcoes: ["Lulu", "Cho'Gath", "Zac", "Malphite"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Requiem'?", opcoes: ["Karthus", "Yorick", "Mordekaiser", "Nocturne"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Destino'?", opcoes: ["Twisted Fate", "Ekko", "Ryze", "Bardo"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Aparar'?", opcoes: ["Fiora", "Jax", "Master Yi", "Riven"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Invasão Umbral'?", opcoes: ["Kayn", "Zed", "Talon", "Nocturne"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Último Suspiro'?", opcoes: ["Yasuo", "Yone", "Master Yi", "Xin Zhao"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Tiro de Precisão'?", opcoes: ["Ezreal", "Caitlyn", "Ashe", "Jinx"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Morte vinda de Baixo'?", opcoes: ["Pyke", "Nautilus", "Fizz", "Urgot"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Atratividade Magnética'?", opcoes: ["Rell", "Leona", "Taric", "Braum"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Comando: Onda de Choque'?", opcoes: ["Orianna", "Syndra", "Viktor", "Lulu"], correta: 0 },
    { pergunta: "De quem é a habilidade 'A Face da Montanha'?", opcoes: ["Malphite", "Maokai", "Ornn", "Galio"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Explosão Primordial'?", opcoes: ["Veigar", "Syndra", "Brand", "Annie"], correta: 0 },
    { pergunta: "De quem é a habilidade 'O Show Deve Continuar'?", opcoes: ["Sett", "Vi", "Lee Sin", "Braum"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Asas Quebradas'?", opcoes: ["Riven", "Fiora", "Irelia", "Aatrox"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Lâmina do Exílio'?", opcoes: ["Riven", "Yasuo", "Aatrox", "Tryndamere"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Devorar'?", opcoes: ["Tahm Kench", "Nunu e Willump", "Cho'Gath", "Kog'Maw"], correta: 1 },
    { pergunta: "De quem é a habilidade 'Banquete'?", opcoes: ["Cho'Gath", "Tahm Kench", "Nunu e Willump", "Warwick"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Paranoia'?", opcoes: ["Nocturne", "Shaco", "Fiddlesticks", "Evelynn"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Crescendo'?", opcoes: ["Sona", "Seraphine", "Bardo", "Rakan"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ritual Arcano'?", opcoes: ["Xerath", "Vel'Koz", "Karthus", "Ryze"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Desintegrar'?", opcoes: ["Vel'Koz", "Xerath", "Malzahar", "Kog'Maw"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Aperto Infernal'?", opcoes: ["Malzahar", "Warwick", "Skarner", "Thresh"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Poder de Demacia'?", opcoes: ["Garen", "Jarvan IV", "Lux", "Xin Zhao"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Flecha de Cristal Encantada'?", opcoes: ["Ashe", "Varus", "Vayne", "Quinn"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Barragem de Chumbo'?", opcoes: ["Graves", "Lucian", "Miss Fortune", "Jhin"], correta: 0 },
    { pergunta: "De quem é a habilidade 'O Grande Finale'?", opcoes: ["Jhin", "Draven", "Ezreal", "Varus"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Portal de Reinos'?", opcoes: ["Ryze", "Bardo", "Twisted Fate", "Ekko"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Cataclismo'?", opcoes: ["Jarvan IV", "Malphite", "Taliyah", "Yorick"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Impacto Meteoro'?", opcoes: ["Pantheon", "Galio", "Malphite", "Zac"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Gatilho Desenfreado'?", opcoes: ["Samira", "Katarina", "Samira", "Nilah"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Dominar'?", opcoes: ["Mordekaiser", "Renekton", "Nasus", "Sion"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ragnarok'?", opcoes: ["Olaf", "Tryndamere", "Volibear", "Udyr"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Tempestade de Corvos'?", opcoes: ["Fiddlesticks", "Swain", "Nocturne", "Morgana"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Mergulho Abissal'?", opcoes: ["Rek'Sai", "Nautilus", "Fizz", "Pyke"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Linha de Frente'?", opcoes: ["Nautilus", "Blitzcrank", "Thresh", "Leona"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Sopro de Luz'?", opcoes: ["Aurelion Sol", "Smolder", "Shyvana", "Brand"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Mããããe!'?", opcoes: ["Smolder", "Kog'Maw", "Gnar", "Annie"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Frenesi Sanguinário'?", opcoes: ["Briar", "Warwick", "Vladimir", "Rengar"], correta: 0 },
    { pergunta: "De quem é a habilidade 'A Caminho do Herói'?", opcoes: ["K'Sante", "Jax", "Malphite", "Skarner"], correta: 0 },
    { pergunta: "De quem é a habilidade 'O Chamado do Deus da Forja'?", opcoes: ["Ornn", "Volibear", "Anivia", "Braum"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Grande Estrela Cadente'?", opcoes: ["Pantheon", "Aurelion Sol", "Galio", "Leona"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Chuva Estelar'?", opcoes: ["Soraka", "Karthus", "Sona", "Lux"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Cárcere de Gelo'?", opcoes: ["Sejuani", "Lissandra", "Ashe", "Anivia"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Túmulo Gelado'?", opcoes: ["Lissandra", "Anivia", "Ashe", "Sejuani"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Selo de Malícia'?", opcoes: ["LeBlanc", "Neeko", "Ahri", "Zoe"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Pintura Final'?", opcoes: ["Hwei", "Ahri", "Karma", "Janna"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Super Mega Foguete da Morte!'?", opcoes: ["Jinx", "Ziggs", "Tristana", "Corki"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Vassoura de Aço'?", opcoes: ["Camille", "Irelia", "Fiora", "Vi"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Assalto e Bateria'?", opcoes: ["Vi", "Sett", "Lee Sin", "Nautilus"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ira do Dragão'?", opcoes: ["Lee Sin", "Shyvana", "Aurelion Sol", "Jarvan IV"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Coração da Tempestade'?", opcoes: ["Kennen", "Volibear", "Janna", "Anivia"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Destino Selado'?", opcoes: ["Yone", "Yasuo", "Zed", "Shen"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Marca do Assassino'?", opcoes: ["Akali", "Talon", "Zed", "Katarina"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Pequeno Mestre do Mal'?", opcoes: ["Veigar", "Teemo", "Ziggs", "Tristana"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Hemorragia'?", opcoes: ["Darius", "Draven", "Vladimir", "Talon"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Fervor Jônico'?", opcoes: ["Irelia", "Akali", "Karma", "Ahri"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Lâminas da Vanguarda'?", opcoes: ["Irelia", "Katarina", "Akali", "Talon"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Dama da Luz'?", opcoes: ["Lux", "Morgana", "Leona", "Seraphine"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Luz Final'?", opcoes: ["Lux", "Morgana", "Senna", "Ezreal"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Aparência Estonteante'?", opcoes: ["Taric", "Rakan", "Braum", "Leona"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Esplendor Cósmico'?", opcoes: ["Taric", "Soraka", "Bardo", "Aurelion Sol"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ponto de Ruptura'?", opcoes: ["Rell", "Leona", "Taric", "Alistar"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Abaixo de Zero'?", opcoes: ["Nunu e Willump", "Anivia", "Lissandra", "Braum"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Monção'?", opcoes: ["Janna", "Soraka", "Nami", "Lulu"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Divisor de Marés'?", opcoes: ["Nami", "Fizz", "Nautilus", "Pyke"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Brincadeira/Trote'?", opcoes: ["Fizz", "Shaco", "Zoe", "Neeko"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Lançar Isca'?", opcoes: ["Fizz", "Nami", "Tahm Kench", "Pyke"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Petrificação'?", opcoes: ["Cassiopeia", "Medusa", "Morgana", "Zyra"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Mundo de Sombras'?", opcoes: ["Nocturne", "Mordekaiser", "Senna", "Vex"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Possessão'?", opcoes: ["Viego", "Sylas", "Mordekaiser", "Yorick"], correta: 0 },
    { pergunta: "De quem é a habilidade 'O Chamado do Destino'?", opcoes: ["Kalista", "Thresh", "Senna", "Lucian"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Sopro de Vida'?", opcoes: ["Milio", "Soraka", "Yuumi", "Janna"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Execução Pública'?", opcoes: ["Ambessa", "Darius", "Draven", "Urgot"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Impacto Chocante'?", opcoes: ["Heimerdinger", "Ziggs", "Corki", "Rumble"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Equalizador'?", opcoes: ["Rumble", "Viktor", "Jayce", "Heimerdinger"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Tempestade Magnética'?", opcoes: ["Viktor", "Blitzcrank", "Orianna", "Rumble"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Transformação: Martelo de Mercúrio'?", opcoes: ["Jayce", "Viktor", "Ekko", "Vi"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Grito do Carniceiro'?", opcoes: ["Urgot", "Sion", "Dr. Mundo", "Singed"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Glória na Morte'?", opcoes: ["Sion", "Karthus", "Yorick", "Mordekaiser"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Evolução Icathiana'?", opcoes: ["Kai'Sa", "Kha'Zix", "Vel'Koz", "Kog'Maw"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Instinto Assassino'?", opcoes: ["Kai'Sa", "Akali", "Katarina", "Samira"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Chuva Icathiana'?", opcoes: ["Kai'Sa", "Kog'Maw", "Vel'Koz", "Kha'Zix"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Vingança Incandescente'?", opcoes: ["Brand", "Annie", "Ornn", "Shyvana"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Tibbers'?", opcoes: ["Annie", "Lulu", "Yuumi", "Zoe"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Estímulo'?", opcoes: ["Singed", "Dr. Mundo", "Twitch", "Warwick"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Rastro de Veneno'?", opcoes: ["Singed", "Twitch", "Teemo", "Cassiopeia"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Surpresa de Icathia'?", opcoes: ["Kog'Maw", "Cho'Gath", "Vel'Koz", "Kha'Zix"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Artilharia Viva'?", opcoes: ["Kog'Maw", "Xerath", "Vel'Koz", "Ezreal"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Salto de Fé'?", opcoes: ["Illaoi", "Malphite", "Zac", "Jarvan IV"], correta: 0 },
    { pergunta: "De quem é a habilidade 'A Caminho do Sul'?", opcoes: ["Kled", "Sion", "Hecarim", "Rammus"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Massacre'?", opcoes: ["Aatrox", "Master Yi", "Olaf", "Tryndamere"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Aparência Estonteante'?", opcoes: ["Taric", "Bardo", "Rakan", "Leona"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ritual de Sangue'?", opcoes: ["Vladimir", "Briar", "Swain", "Renata Glasc"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Hemoplaga'?", opcoes: ["Vladimir", "Warwick", "Swain", "Briar"], correta: 0 },
    { pergunta: "De quem é a habilidade 'A Tocha de Pix'?", opcoes: ["Lulu", "Yuumi", "Zoe", "Annie"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Pai do Verde'?", opcoes: ["Ivern", "Maokai", "Zyra", "Malphite"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Semente de Detonação'?", opcoes: ["Ivern", "Zyra", "Maokai", "Lillia"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Pancada de Casco'?", opcoes: ["Alistar", "Malphite", "Hecarim", "Sejuani"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Vontade de Ferro'?", opcoes: ["Lee Sin", "Garen", "Alistar", "Jarvan IV"], correta: 2 },
    { pergunta: "De quem é a habilidade 'Pulverizar'?", opcoes: ["Alistar", "Malphite", "Sett", "Vi"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Mergulho do Dragão'?", opcoes: ["Jarvan IV", "Shyvana", "Lee Sin", "Aurelion Sol"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Estandarte Demaciano'?", opcoes: ["Jarvan IV", "Garen", "Xin Zhao", "Lux"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ataque de Relâmpago'?", opcoes: ["Kennen", "Volibear", "Master Yi", "Blitzcrank"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Shuriken Fulminante'?", opcoes: ["Kennen", "Akali", "Zed", "Shen"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Chamado do Mar'?", opcoes: ["Nami", "Fizz", "Nautilus", "Tahm Kench"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Prisão Aquática'?", opcoes: ["Nami", "Fizz", "Lux", "Morgana"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Fluxo de Essência'?", opcoes: ["Ezreal", "Ryze", "Kassadin", "Taric"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Transpôr'?", opcoes: ["Ezreal", "Kassadin", "Ekko", "Zoe"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Barragem Incendiária'?", opcoes: ["Corki", "Rumble", "Gangplank", "Ziggs"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Entrega Especial'?", opcoes: ["Corki", "Taliyah", "Pantheon", "Galio"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Bomba de Fumaça'?", opcoes: ["Graves", "Akali", "Talon", "Teemo"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Saque Rápido'?", opcoes: ["Graves", "Lucian", "Vayne", "Kindred"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Vingança Incandescente'?", opcoes: ["Brand", "Annie", "Ornn", "Shyvana"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Pilar de Chamas'?", opcoes: ["Brand", "Trundle", "Anivia", "Ornn"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Desintegrar'?", opcoes: ["Annie", "Vel'Koz", "Xerath", "Veigar"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Escudo Fundido'?", opcoes: ["Annie", "Rumble", "Mordekaiser", "Malphite"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Gume de Lâmina'?", opcoes: ["Talon", "Katarina", "Zed", "Draven"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Diplomacia Noxiana'?", opcoes: ["Talon", "Darius", "Katarina", "Leblanc"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ataque de Fome'?", opcoes: ["Warwick", "Briar", "Nunu", "Tahm Kench"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Caçada Sangrenta'?", opcoes: ["Warwick", "Rengar", "Kha'Zix", "Briar"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Sopro de Inverno'?", opcoes: ["Braum", "Anivia", "Lissandra", "Sejuani"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Eu te Protejo'?", opcoes: ["Braum", "Rakan", "Yuumi", "Shen"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Estilo Wuju'?", opcoes: ["Master Yi", "Yasuo", "Yone", "Jax"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ataque Alpha'?", opcoes: ["Master Yi", "Warwick", "Rengar", "Kha'Zix"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Golpe de Vento'?", opcoes: ["Yasuo", "Yone", "Riven", "Janna"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Parede de Vento'?", opcoes: ["Yasuo", "Braum", "Samira", "Xin Zhao"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Aço Letal'?", opcoes: ["Yone", "Yasuo", "Master Yi", "Xin Zhao"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Desatar a Alma'?", opcoes: ["Yone", "Senna", "Karthus", "Thresh"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Sobra Viva'?", opcoes: ["Zed", "Shaco", "Kayn", "Leblanc"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Corte Sombrio'?", opcoes: ["Zed", "Kayn", "Talon", "Nocturne"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Fúria da Batalha'?", opcoes: ["Tryndamere", "Olaf", "Renekton", "Aatrox"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Grito de Zombaria'?", opcoes: ["Tryndamere", "Rammus", "Galio", "Shaco"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Balanço de Poder'?", opcoes: ["Kassadin", "Ryze", "Malzahar", "Azir"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Pulso de Força'?", opcoes: ["Kassadin", "Viktor", "Jayce", "Vel'Koz"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Lâmina Infernal'?", opcoes: ["Kassadin", "Aatrox", "Mordekaiser", "Kayle"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Proteção de Targon'?", opcoes: ["Leona", "Taric", "Pantheon", "Diana"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Eclipse'?", opcoes: ["Leona", "Diana", "Soraka", "Aurelion Sol"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Lâmina Lúnar'?", opcoes: ["Diana", "Leona", "Aphelios", "Yasuo"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Cascata Pálida'?", opcoes: ["Diana", "Morgana", "Lux", "Senna"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Chamado do Vazio'?", opcoes: ["Malzahar", "Kassadin", "Kai'Sa", "Bel'Veth"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Zonas de Vazio'?", opcoes: ["Malzahar", "Vel'Koz", "Kha'Zix", "Cho'Gath"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Grito Selvagem'?", opcoes: ["Cho'Gath", "Gnar", "Warwick", "Volibear"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Espinhos Vorpal'?", opcoes: ["Cho'Gath", "Zyra", "Evelynn", "Rammus"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Sabor de Medo'?", opcoes: ["Kha'Zix", "Rengar", "Evelynn", "Nocturne"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Espinho do Vazio'?", opcoes: ["Kha'Zix", "Cho'Gath", "Vel'Koz", "Malzahar"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ameaça Invisível'?", opcoes: ["Kha'Zix", "Rengar", "Shaco", "Evelynn"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Predador Oculto'?", opcoes: ["Rengar", "Nidalee", "Kha'Zix", "Warwick"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Boleadeiras'?", opcoes: ["Rengar", "Nilah", "Graves", "Akshan"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Selvageria'?", opcoes: ["Rengar", "Warwick", "Udyr", "Nidalee"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Arremesso de Lança'?", opcoes: ["Nidalee", "Pantheon", "Kalista", "Xin Zhao"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ímpeto Primal'?", opcoes: ["Nidalee", "Gnar", "Renekton", "Udyr"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Besta de Repetição'?", opcoes: ["Twitch", "Vayne", "Quinn", "Varus"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Emboscada'?", opcoes: ["Twitch", "Shaco", "Rengar", "Evelynn"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Contaminar'?", opcoes: ["Twitch", "Cassiopeia", "Singed", "Teemo"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Flecha Perfurante'?", opcoes: ["Varus", "Ashe", "Sivir", "Caitlyn"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Chuva de Flechas'?", opcoes: ["Varus", "Ashe", "Quinn", "Kindred"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Corrente da Corrupção'?", opcoes: ["Varus", "Morgana", "Thresh", "LeBlanc"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Selo de Malícia'?", opcoes: ["LeBlanc", "Zoe", "Ahri", "Neeko"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Distorção'?", opcoes: ["LeBlanc", "Ekko", "Kassadin", "Ezreal"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Correntes Etéreas'?", opcoes: ["LeBlanc", "Sylas", "Karma", "Thresh"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Dominação Divina'?", opcoes: ["Renekton", "Nasus", "Azir", "Aatrox"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Fatia e Pica'?", opcoes: ["Renekton", "Darius", "Talon", "Riven"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Predador Implacável'?", opcoes: ["Renekton", "Rengar", "Warwick", "Kha'Zix"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Lâminas Mortais'?", opcoes: ["Draven", "Katarina", "Talon", "Irelia"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Revolução do Machado'?", opcoes: ["Draven", "Olaf", "Darius", "Sion"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Adicionar Pressão'?", opcoes: ["Draven", "Jinx", "Ezreal", "Twitch"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Carga Devastadora'?", opcoes: ["Hecarim", "Sion", "Rammus", "Kled"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Espírito do Pavor'?", opcoes: ["Hecarim", "Fiddlesticks", "Karthus", "Nocturne"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ataque de Áurea'?", opcoes: ["Xin Zhao", "Jarvan IV", "Garen", "Pantheon"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Vento de Batalha'?", opcoes: ["Galio", "Yasuo", "Janna", "Anivia"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Escudo de Durand'?", opcoes: ["Galio", "Garen", "Leona", "Braum"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Soco de Justiça'?", opcoes: ["Galio", "Vi", "Sett", "Lee Sin"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Orbe da Decepção'?", opcoes: ["Ahri", "Orianna", "Syndra", "Lulu"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Fogo de Raposa'?", opcoes: ["Ahri", "Annie", "Brand", "Kennen"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Fervor Jônico'?", opcoes: ["Irelia", "Karma", "Ahri", "Yasuo"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Surto de Adrenalina'?", opcoes: ["Dr. Mundo", "Olaf", "Renekton", "Singed"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Cutelo Infectado'?", opcoes: ["Dr. Mundo", "Olaf", "Sion", "Twitch"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Choque Ardente'?", opcoes: ["Udyr", "Brand", "Shyvana", "Annie"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Manto de Chamas'?", opcoes: ["Shyvana", "Brand", "Annie", "Ornn"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Hálito Flamejante'?", opcoes: ["Shyvana", "Aurelion Sol", "Smolder", "Brand"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Morte Texturizada'?", opcoes: ["Hwei", "Jhin", "Aphelios", "Senna"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Assinatura Visionária'?", opcoes: ["Hwei", "Seraphine", "Sona", "Lux"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ataque de Lança'?", opcoes: ["Pantheon", "Xin Zhao", "Jarvan IV", "Nidalee"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Escudo de Batalha'?", opcoes: ["Pantheon", "Leona", "Braum", "Garen"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Bombardeio de Sementes'?", opcoes: ["Zyra", "Ivern", "Maokai", "Lulu"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Crescimento Desenfreado'?", opcoes: ["Zyra", "Maokai", "Ivern", "Lillia"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Pilar de Gelo'?", opcoes: ["Trundle", "Anivia", "Braum", "Lissandra"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Subjugas'?", opcoes: ["Trundle", "Mordekaiser", "Sylas", "Nasus"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Lâmina Estelar'?", opcoes: ["Kayle", "Diana", "Leona", "Taric"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Julgamento Celestial'?", opcoes: ["Kayle", "Morgana", "Leona", "Pantheon"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Sombra de Chamas'?", opcoes: ["Naafiri", "Zed", "Kayn", "Shaco"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Alcance da Matilha'?", opcoes: ["Naafiri", "Warwick", "Rengar", "Kindred"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Fogo Amigo'?", opcoes: ["Milio", "Annie", "Brand", "Tristana"], correta: 0 },
    { pergunta: "De quem é a habilidade 'Ultramega Chute Flamejante'?", opcoes: ["Milio", "Lee Sin", "Sett", "Vi"], correta: 0 }
