// pergunta.js (Cole exatamente isso)
export const bancoPerguntas = [

    { pergunta: "Qual campeão é conhecido como o 'Orgulho de Nazumah'?", opcoes: ["K'Sante", "Jax", "Malphite", "Skarner"], correta: 0 },
    { pergunta: "Qual a cor da barra de energia do Kennen?", opcoes: ["Azul", "Amarela", "Branca", "Roxa"], correta: 1 },
    { pergunta: "Quantos jogadores há em cada equipa no Rift?", opcoes: ["3", "4", "5", "6"], correta: 2 },
    { pergunta: "Qual campeão atira cartas coloridas?", opcoes: ["Twisted Fate", "Ezreal", "Graves", "Lucian"], correta: 0 },
    { pergunta: "Qual o nome da passiva da Anivia?", opcoes: ["Gelo", "Renascimento", "Ovo", "Frio"], correta: 2 },
    { pergunta: "Quem é o suporte da Xayah?", opcoes: ["Rakan", "Thresh", "Braum", "Blitzcrank"], correta: 0 },
    { pergunta: "Qual destes campeões é um gato?", opcoes: ["Nidalee", "Yuumi", "Rengar", "Twitch"], correta: 1 },
    { pergunta: "Qual a arma principal da Caitlyn?", opcoes: ["Pistola", "Arco", "Rifle", "Besta"], correta: 2 },
    { pergunta: "Qual campeão tem uma Ultimate chamada 'Crescimento Gigante'?", opcoes: ["Cho'Gath", "Lulu", "Malphite", "Zac"], correta: 1 },
    { pergunta: "Qual monstro do rio dá regeneração de vida e mana?", opcoes: ["Dragão", "Aronguejo", "Barão", "Gromp"], correta: 1 },
    { pergunta: "Qual é o apelido da Lux?", opcoes: ["A Dama da Luz", "A Sombra", "A Lâmina", "A Estrela"], correta: 0 },
    { pergunta: "Quem é o pai da Cassiopeia e da Katarina?", opcoes: ["Swain", "Darius", "Du Couteau", "Garen"], correta: 2 },
    { pergunta: "Qual item é conhecido como 'Zhonya'?", opcoes: ["Cetro de Cristal", "Ampulheta de Zhonya", "Gume do Infinito", "Cajado do Vazio"], correta: 1 },
    { pergunta: "Qual destes feitiços dá um 'pulo' instantâneo?", opcoes: ["Fantasma", "Flash", "Exaustão", "Barreira"], correta: 1 },
    { pergunta: "Qual a nacionalidade do Braum?", opcoes: ["Demacia", "Freljord", "Noxus", "Ionia"], correta: 1 },
    { pergunta: "Qual campeão usa um escudo enorme e protege poros?", opcoes: ["Leona", "Braum", "Alistar", "Taric"], correta: 1 },
    { pergunta: "Qual campeão vira uma aranha?", opcoes: ["Elise", "Nidalee", "Zyra", "Evelynn"], correta: 0 },
    { pergunta: "Qual a classe do Garen?", opcoes: ["Mago", "Atirador", "Lutador/Tanque", "Suporte"], correta: 2 },
    { pergunta: "Qual o nome da cidade tecnológica vizinha de Zaun?", opcoes: ["Noxus", "Demacia", "Piltover", "Ionia"], correta: 2 },
    { pergunta: "Qual campeão puxa inimigos com uma âncora?", opcoes: ["Thresh", "Nautilus", "Blitzcrank", "Pyke"], correta: 1 },
    { pergunta: "Qual o elemento do Dragão que muda o mapa com matos?", opcoes: ["Fogo", "Oceano", "Nuvens", "Montanha"], correta: 1 },
    { pergunta: "Qual o elemento do Dragão que cria paredes novas?", opcoes: ["Fogo", "Oceano", "Nuvens", "Montanha"], correta: 3 },
    { pergunta: "Qual campeão é um espantalho?", opcoes: ["Fiddlesticks", "Shaco", "Nocturne", "Hecarim"], correta: 0 },
    { pergunta: "Qual o nome da arma da Miss Fortune?", opcoes: ["Chumbo Grosso", "Choque e Pavor", "Sussurro", "Besta"], correta: 1 },
    { pergunta: "Quantas skins de equipas campeãs mundiais existem?", opcoes: ["Nenhuma", "Muitas", "Uma por ano", "Apenas 3"], correta: 2 },
    { pergunta: "Qual campeã usa um chicote de espinhos?", opcoes: ["Zyra", "Leona", "Evelynn", "Lissandra"], correta: 2 },
    { pergunta: "Quem é o explorador de Piltover que usa uma manopla?", opcoes: ["Jayce", "Ezreal", "Vi", "Ekko"], correta: 1 },
    { pergunta: "Qual campeão come os inimigos para crescer?", opcoes: ["Cho'Gath", "Tahm Kench", "Nunu", "Gnar"], correta: 0 },
    { pergunta: "Qual o nome do urso do Volibear?", opcoes: ["Tibbers", "Daisy", "Ele próprio", "Ursa"], correta: 2 },
    { pergunta: "Qual a arma do Yasuo?", opcoes: ["Adaga", "Katana", "Machado", "Lança"], correta: 1 },
    { pergunta: "Qual campeão é um gladiador de Noxus?", opcoes: ["Draven", "Darius", "Katarina", "Talon"], correta: 0 },
    { pergunta: "O que o item 'Gume do Infinito' aumenta?", opcoes: ["Vida", "Dano Crítico", "Mana", "Velocidade"], correta: 1 },
    { pergunta: "Qual campeão é um rato da selva?", opcoes: ["Twitch", "Teemo", "Kennen", "Ziggs"], correta: 0 },
    { pergunta: "Qual campeã joga bolas de fogo?", opcoes: ["Lux", "Annie", "Ahri", "Karma"], correta: 1 },
    { pergunta: "Qual campeã tem nove caudas?", opcoes: ["Ahri", "Evelynn", "Akali", "Kai'Sa"], correta: 0 },
    { pergunta: "Qual campeão usa um martelo que vira canhão?", opcoes: ["Jayce", "Poppy", "Ornn", "Tristana"], correta: 0 },
    { pergunta: "Qual feitiço de invocador serve para curar?", opcoes: ["Curar", "Incendiar", "Exaustão", "Clareza"], correta: 0 },
    { pergunta: "Qual campeão joga barris de bebida?", opcoes: ["Gragas", "Gangplank", "Singed", "Bardo"], correta: 0 },
    { pergunta: "Qual o nome da espada do Aatrox?", opcoes: ["Espada da Ruína", "A Lâmina Darkin", "Gume", "Excalibur"], correta: 1 },
    { pergunta: "Quem é a esposa de Lucian?", opcoes: ["Senna", "Vayne", "Quinn", "Sivir"], correta: 0 },
    { pergunta: "Qual campeão é feito de rocha?", opcoes: ["Malphite", "Galio", "Rammus", "Skarner"], correta: 0 },
    { pergunta: "Qual o nome da Ultimate do Karthus?", opcoes: ["Requiem", "Final Spark", "Chuva de Flechas", "Impacto"], correta: 0 },
    { pergunta: "Qual campeão é um tubarão (ou invoca um)?", opcoes: ["Fizz", "Nami", "Pyke", "Nautilus"], correta: 0 },
    { pergunta: "Qual o nome da passiva do Yasuo?", opcoes: ["Vento", "Caminho do Vagabundo", "Crítico", "Escudo"], correta: 1 },
    { pergunta: "Quem é a xerife de Piltover?", opcoes: ["Vi", "Caitlyn", "Jinx", "Camille"], correta: 1 },
    { pergunta: "Qual campeão corre muito rápido e diz 'OK'?", opcoes: ["Singed", "Rammus", "Hecarim", "Master Yi"], correta: 1 },
    { pergunta: "Qual o nome da ilha onde vivem os fantasmas?", opcoes: ["Ionia", "Ilha das Sombras", "Bilgewater", "Targon"], correta: 1 },
    { pergunta: "Qual campeão usa lanternas para salvar aliados?", opcoes: ["Thresh", "Jax", "Lulu", "Karma"], correta: 0 },
    { pergunta: "Qual a cor do 'Red Buff'?", opcoes: ["Azul", "Verde", "Vermelho", "Amarelo"], correta: 2 },
    { pergunta: "Qual a cor do 'Blue Buff'?", opcoes: ["Azul", "Roxo", "Ciano", "Verde"], correta: 0 },
    { pergunta: "Qual campeão atira bananas (ataque básico)?", opcoes: ["Soraka", "Lulu", "Wukong", "Nidalee"], correta: 0 },
    { pergunta: "Qual o nome da arma do Gangplank?", opcoes: ["Pistola e Sabre", "Tridente", "Canhão", "Besta"], correta: 0 },
    { pergunta: "Qual campeão é um bardo?", opcoes: ["Bardo", "Sona", "Seraphine", "Taric"], correta: 0 },
    { pergunta: "Qual campeã toca harpa?", opcoes: ["Sona", "Seraphine", "Janna", "Nami"], correta: 0 },
    { pergunta: "Qual campeão é o mestre das sombras?", opcoes: ["Zed", "Shen", "Akali", "Kayn"], correta: 0 },
    { pergunta: "Qual campeão é o olho do crepúsculo?", opcoes: ["Shen", "Kennen", "Zed", "Lee Sin"], correta: 0 },
    { pergunta: "Qual campeão é um ninja médico?", opcoes: ["Akali", "Shen", "Kennen", "Lee Sin"], correta: 1 },
    { pergunta: "Qual campeão usa um boomerang?", opcoes: ["Gnar", "Sivir", "Akshan", "Draven"], correta: 1 },
    { pergunta: "Qual campeão vira uma mega criatura quando a fúria enche?", opcoes: ["Gnar", "Shyvana", "Tryndamere", "Renekton"], correta: 0 },
    { pergunta: "Qual campeão é um pirata?", opcoes: ["Gangplank", "Graves", "Pyke", "Nautilus"], correta: 0 },
    { pergunta: "Qual campeã usa cartas de Tarot?", opcoes: ["Lux", "Ahri", "Twisted Fate", "Leblanc"], correta: 2 },
    { pergunta: "Qual campeão é um palhaço assassino?", opcoes: ["Shaco", "Fiddlesticks", "Nocturne", "Pyke"], correta: 0 },
    { pergunta: "Qual campeã é a mãe da nidalee no folclore (brincadeira)?", opcoes: ["Neeko", "Zyra", "Lulu", "LeBlanc"], correta: 0 },
    { pergunta: "Qual campeão é um dragão de verdade?", opcoes: ["Aurelion Sol", "Shyvana", "Jarvan IV", "Pantheon"], correta: 0 },
    { pergunta: "Qual campeão forja itens na base?", opcoes: ["Ornn", "Braum", "Gragas", "Udyr"], correta: 0 },
    { pergunta: "Qual o nome do dragão da Annie?", opcoes: ["Tibbers", "Rex", "Daisy", "Bolinha"], correta: 0 },
    { pergunta: "Qual campeão usa uma pá?", opcoes: ["Yorick", "Sion", "Karthus", "Urgot"], correta: 0 },
    { pergunta: "Qual campeã é uma sereia?", opcoes: ["Nami", "Fizz", "Cassiopeia", "Morgana"], correta: 0 },
    { pergunta: "Qual campeã joga veneno no chão e corre?", opcoes: ["Singed", "Cassiopeia", "Twitch", "Teemo"], correta: 0 },
    { pergunta: "Qual campeão é o açougueiro das areias?", opcoes: ["Renekton", "Nasus", "Azir", "Sivir"], correta: 0 },
    { pergunta: "Qual campeão é um deus egípcio chacal?", opcoes: ["Nasus", "Renekton", "Azir", "Xerath"], correta: 0 },
    { pergunta: "Qual campeão invoca soldados de areia?", opcoes: ["Azir", "Nasus", "Renekton", "Xerath"], correta: 0 },
    { pergunta: "Qual campeão é um golem de vapor?", opcoes: ["Blitzcrank", "Viktor", "Orianna", "Urgot"], correta: 0 },
    { pergunta: "Qual campeã é uma boneca robô?", opcoes: ["Orianna", "Gwen", "Annie", "Zoe"], correta: 0 },
    { pergunta: "Qual campeã usa tesouras gigantes?", opcoes: ["Gwen", "Camille", "Fiora", "Irelia"], correta: 0 },
    { pergunta: "Qual campeã é a grande duelista?", opcoes: ["Fiora", "Irelia", "Riven", "Camille"], correta: 0 },
    { pergunta: "Qual campeã usa pernas de lâmina?", opcoes: ["Camille", "Fiora", "Katarina", "Evelynn"], correta: 0 },
    { pergunta: "Qual campeão é o rei dos trolls?", opcoes: ["Trundle", "Gragas", "Olaf", "Braum"], correta: 0 },
    { pergunta: "Qual campeão usa um machado e não morre na ult?", opcoes: ["Tryndamere", "Olaf", "Darius", "Sion"], correta: 0 },
    { pergunta: "Qual campeão é o mestre do metal?", opcoes: ["Mordekaiser", "Taric", "Malphite", "Skarner"], correta: 0 },
    { pergunta: "Qual campeã é a luz de Demacia?", opcoes: ["Lux", "Morgana", "Kayle", "Vayne"], correta: 0 },
    { pergunta: "Qual campeã é o anjo caído?", opcoes: ["Morgana", "Kayle", "Leblanc", "Sivir"], correta: 0 },
    { pergunta: "Qual campeã é a guardiã do martelo?", opcoes: ["Poppy", "Tristana", "Lulu", "Yuumi"], correta: 0 },
    { pergunta: "Qual campeã é a artilheira Yordle?", opcoes: ["Tristana", "Poppy", "Lulu", "Ziggs"], correta: 0 },
    { pergunta: "Qual campeão joga bombas?", opcoes: ["Ziggs", "Zilean", "Teemo", "Heimerdinger"], correta: 0 },
    { pergunta: "Qual campeão controla o tempo?", opcoes: ["Zilean", "Ekko", "Lucian", "Ryze"], correta: 0 },
    { pergunta: "Qual campeão viaja no tempo com a ult?", opcoes: ["Ekko", "Zilean", "Ezreal", "Jayce"], correta: 0 },
    { pergunta: "Qual campeão é o mago das runas?", opcoes: ["Ryze", "Brand", "Malzahar", "Kassadin"], correta: 0 },
    { pergunta: "Qual campeão é o mago de fogo?", opcoes: ["Brand", "Annie", "Ryze", "Xerath"], correta: 0 },
    { pergunta: "Qual campeão é o profeta do vazio?", opcoes: ["Malzahar", "Kassadin", "Kha'Zix", "Vel'Koz"], correta: 0 },
    { pergunta: "Qual campeão é um polvo do vazio com lasers?", opcoes: ["Vel'Koz", "Kha'Zix", "Cho'Gath", "Kog'Maw"], correta: 0 },
    { pergunta: "Qual campeão é o louco de Zaun?", opcoes: ["Dr. Mundo", "Singed", "Twitch", "Warwick"], correta: 0 },
    { pergunta: "Qual campeão é um lobisomem?", opcoes: ["Warwick", "Nidalee", "Udyr", "Rengar"], correta: 0 },
    { pergunta: "Qual campeão é um leão caçador?", opcoes: ["Rengar", "Nidalee", "Warwick", "Khazix"], correta: 0 },
    { pergunta: "Qual campeão é um inseto que evolui?", opcoes: ["Kha'Zix", "Rengar", "Skarner", "Elise"], correta: 0 },
    { pergunta: "Qual campeão usa um chicote de luz (lança)?", opcoes: ["Xin Zhao", "Jarvan IV", "Pantheon", "Jax"], correta: 0 },
    { pergunta: "Qual campeão é o príncipe de Demacia?", opcoes: ["Jarvan IV", "Garen", "Lux", "Galio"], correta: 0 },
    { pergunta: "Qual campeão é o artesão da guerra?", opcoes: ["Pantheon", "Aatrox", "Mordekaiser", "Sion"], correta: 0 },
    { pergunta: "Qual campeão é uma gárgula?", opcoes: ["Galio", "Malphite", "Maokai", "Ivern"], correta: 0 }
];
